automation.qmetry.enabled = true
automation.qmetry.debug = true
automation.qmetry.url=https://qtmcloud.qmetry.com/rest/api/automation/importresult
automation.qmetry.apikey = 21aa546916a500020bc2f1b3edeed901c5f2150ddf3ce873072feae728866a05ddb571474447d105da22a7563a6d2d454622af88b50f8d275719adfdfe582a9eae55bbe7f418b9c0571b68099a3e2329
automation.qmetry.filepath=target/cucumber-json-report.json
automation.qmetry.environment=Certificación
automation.qmetry.build=
automation.qmetry.attachfile=true
automation.qmetry.matchTestSteps=
automation.qmetry.testCycleToReuse=
automation.qmetry.testcycle.summary=
automation.qmetry.testcycle.labels=
automation.qmetry.testcycle.components=
automation.qmetry.testcycle.priority=
automation.qmetry.testcycle.status=
automation.qmetry.testcycle.sprintId=
automation.qmetry.testcycle.fixVersionId=
automation.qmetry.testcase.labels=
automation.qmetry.testcase.components=
automation.qmetry.testcase.priority=
automation.qmetry.testcase.status=
automation.qmetry.testcase.sprintId=
automation.qmetry.testcase.fixVersionId=
automation.qmetry.testCaseExecution.customFields=
